### ISSUE TITLE
issue installing gr-foo

### ISSUE THREAD

**Issue by mohammad-shekarifard** [bastibl/gr-foo#7]
Hello Bastian, i am using installation guide of gr-foo here, when i run ' make ' command i see these errors.
![screenshot from 2018-02-16 23-51-02](https://user-images.githubusercontent.com/36436603/36327612-4dc081d6-1374-11e8-96e3-861405285eba.png)

**Comment by bastibl** [comment]
This is strange. Were there any warnings when running `cmake`? Any chances you use a very old version of GNU Radio? Just wild guesses. I've never seen this.... :-/

**Comment by mohammad-shekarifard** [comment]
Hi, the version is GNU Radio Companion 3.7.9 .
when i run 'cmake':
![screenshot from 2018-02-17 10-56-20](https://user-images.githubusercontent.com/36436603/36339170-64ffafc4-13d4-11e8-9c2f-3357ae15b6fd.png)
![screenshot from 2018-02-17 10-56-46](https://user-images.githubusercontent.com/36436603/36339172-6b0ea096-13d4-11e8-9ce5-98915aa9f41c.png)

**Comment by bastibl** [comment]
> Any chances you use a very old version of GNU Radio?

**Comment by bastibl** [comment]
Your GNU Radio is from 2015. I would recommend trying a newer version. (and please, please, please, do not post pictures of text. I don't get why people are doing it these days. This way nobody will find the error through the search function....)

**Comment by arun1993** [comment]
Hi, 
I am getting this error. 

dinesh-wcsnglab-2@wcsnglab-2:~/gr-foo/build$ cmake ..
-- Build type not specified: defaulting to release.
-- UHD library found.
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   system
--   thread
--   chrono
--   date_time
--   atomic
Checking for GNU Radio Module: RUNTIME
 * INCLUDES=/usr/local/include
 * LIBS=/usr/local/lib/libgnuradio-runtime.so;/usr/local/lib/libgnuradio-pmt.so
GNURADIO_RUNTIME_FOUND = TRUE
Checking for GNU Radio Module: ANALOG
 * INCLUDES=/usr/local/include
 * LIBS=/usr/local/lib/libgnuradio-analog.so;/usr/local/lib/libgnuradio-runtime.so;/usr/local/lib/libgnuradio-pmt.so;/usr/local/lib/libvolk.so
GNURADIO_ANALOG_FOUND = TRUE
Checking for GNU Radio Module: BLOCKS
 * INCLUDES=/usr/local/include
 * LIBS=/usr/local/lib/libgnuradio-blocks.so;/usr/local/lib/libgnuradio-runtime.so;/usr/local/lib/libgnuradio-pmt.so
GNURADIO_BLOCKS_FOUND = TRUE
Checking for GNU Radio Module: FILTER
 * INCLUDES=/usr/local/include
 * LIBS=/usr/local/lib/libgnuradio-filter.so;/usr/local/lib/libgnuradio-fft.so;/usr/local/lib/libgnuradio-runtime.so;/usr/local/lib/libgnuradio-pmt.so
GNURADIO_FILTER_FOUND = TRUE
Checking for GNU Radio Module: PMT
 * INCLUDES=/usr/local/include
 * LIBS=/usr/local/lib/libgnuradio-runtime.so;/usr/local/lib/libgnuradio-pmt.so
GNURADIO_PMT_FOUND = TRUE
-- 
-- Checking for module SWIG
-- Found SWIG version 3.0.8.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dinesh-wcsnglab-2/gr-foo/build
dinesh-wcsnglab-2@wcsnglab-2:~/gr-foo/build$ 
dinesh-wcsnglab-2@wcsnglab-2:~/gr-foo/build$ make
[  4%] Building CXX object lib/CMakeFiles/gnuradio-foo.dir/channel_model_impl.cc.o
In file included from /home/dinesh-wcsnglab-2/gr-foo/lib/channel_model_impl.cc:18:0:
/home/dinesh-wcsnglab-2/gr-foo/lib/channel_model_impl.h:27:47: fatal error: gnuradio/filter/mmse_resampler_cc.h: No such file or directory
compilation terminated.
lib/CMakeFiles/gnuradio-foo.dir/build.make:86: recipe for target 'lib/CMakeFiles/gnuradio-foo.dir/channel_model_impl.cc.o' failed
make[2]: *** [lib/CMakeFiles/gnuradio-foo.dir/channel_model_impl.cc.o] Error 1
CMakeFiles/Makefile2:135: recipe for target 'lib/CMakeFiles/gnuradio-foo.dir/all' failed
make[1]: *** [lib/CMakeFiles/gnuradio-foo.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
dinesh-wcsnglab-2@wcsnglab-2:~/gr-foo/build$ 

dinesh-wcsnglab-2@wcsnglab-2:~/gr-foo$ gnuradio-config-info -v
3.7.10.1

I use 3.7 version and not able to find some blocks in the gr-802.11 because of this. Any suggestion on how to solve this?

**Comment by bastibl** [comment]
Any reason you add this to this issue? Has it anything to do with the above error? Your issue was already addressed several times. See for example https://github.com/bastibl/gr-foo/issues/8.

**Comment by arun1993** [comment]
I am sorry. When I opened issues I came across this and posted it here. I changed my branch to master and it worked now.
